### PR TITLE
Correct french tick, colon, accents and not translated parts

### PR DESCRIPTION
**Pull request by Wadeck**
No associated ticket, just seen them displayed and hurting my eyes

* In french we put a space before and after the ":" (also for "!").
* Replaced some "a" by "à".
* Double tick the single quote to avoid just hidden them.

@reviewbybees

### CODE REVIEW

**Comment by kinow** [comment]
Thanks for doing that @Wadeck . Interesting the space before and after : and ! , TIL.

Looks good to me. Happy to wait another French speaker to review it (alas I know only a handful of words, but I know there are at least 2 other employees from CB that know it?), or merge it as is now.

**Comment by Wadeck** [comment]
@alecharp if you have time to review those french modifications, it could be nice :)

**Comment by Wadeck** [comment]
@reviewbybees done
@kinow we are good to go now ;-)

**Comment by kinow** [comment]
Merged. Merci!!!

**Pull request merged**
